\documentclass{article}
\usepackage{times}
\usepackage{ie07}
\usepackage{hyperref}
\usepackage{amsmath}

<<MainSettings,echo=FALSE,cache=FALSE,warning=FALSE,message=FALSE>>=
# http://www.ibspan.waw.pl/~gagolews/?page=resources&subpage=tips
require("knitr")
require("RColorBrewer", quietly=TRUE)

opts_chunk$set(fig.width=3.6,fig.height=2.9,dev='pdf',dev.args=list(pointsize=8, family="serif"), cache=TRUE, crop=TRUE, echo=FALSE)
knit_hooks$set(crop=hook_pdfcrop)
@

\begin{document}


\title{AN OPEN SOURCE TOOL TO ESTIMATE MASS AND EFFICIENCY OF WIND TURBINE POWER TAKE-OFF SYSTEMS}

\authorname{Ozan Keysan, Markus A. Mueller}
\authoraddr{Institute for Energy Systems, University of Edinburgh, EH93JL, U.K.\\
Email: o.keysan@ed.ac.uk}

\maketitle

\keywords
Wind turbine, mass estimation, direct-drive, gearbox, generator

\abstract
This is where the abstract should be placed. It should
consist of one paragraph and a concise summary of the
material discussed in the article below. It is preferable not
to use footnotes in the abstract or the title. The
acknowledgement for funding organisations etc. is placed
in a separate section at the end of the text. We wish you
success with the preparation of your manuscript.

\section{Introduction}

Far offshore wind turbines can help to exploit the wind energy resources that remained untapped so far. These turbines are planned to be installed as floating platforms due to high water depths. Reliability and mechanical stability is the most important issues of floating wind turbines. The nacelle mass is critical for the mechanical stability of the platform. A heavy nacelle requires larger ballast and increases the installation cost. The type of the power take-off system has a direct effect on the nacelle mass.

Although, doubly-fed induction generator coupled to a multi-stage gearbox the most common power take-off (PTO) type for onshore wind turbines; it may not be the most suitable option for a large offshore wind turbine.

gelistir

Data from manufacturers and literature are collected and then used to predict the  mass and efficiency trend lines for wind turbine components. These components then used to built an open-source tool that can estimate the mass and efficiency of the total PTO system. Users can modify the data and models using the tools defined in Appendix-A.

\section{Power Take-Off Components}

The power take-off components in a wind turbine can be listed as: bearing, shaft, gearbox (if applicable), and generator. 

\subsection{Gearbox}

\subsubsection{Single Stage Gearbox}
Gear ratios up to 15:1 can be obtained using a single stage gearbox \cite{Cotrell2002}. Single-stage gearboxes usually consist of a planetary stage with various numbers of gears depending on the power rating. Single stage gearboxes have fewer gears and bearings than the high-speed gearboxes, so they have a higher reliability. Moreover, their efficiencies are higher than 3-stage gearboxes. In \cite{Matveev2011}, the efficiency of a single stage gearbox is given as:

\begin{equation}
  \text{Efficiency(\%)} = 99.5 - \dfrac{P_{in}}{P_{rated}}
\end{equation}

Mass of a single-stage gearbox coupled with medium-speed generator can be approximated as in \cite{Fingersh2006}:

\begin{equation}
	\text{Mass(t)} = 88.3 \times {T_{in}}^{0.774}
\end{equation}

where $T_{input}$ is the input torque in kNm.

\subsubsection{Multi Stage Gearbox}

The most common gearbox type is three-stage gearbox, which increases the turbine speed to approximately 1500 rpm. The data from three-stage gearbox manufacturers are collected and plotted in \autoref{fig:gearbox}.
The mass of a three-stage gearbox can be expressed in terms of the input torque as presented in \autoref{3G_gearbox}. Data from the following manufacturers are collected; Bosch-Rexroth\cite{bosch}, Winergy\cite{winergy}, Moventas\cite{Moventas}, Eickhoff\cite{eickhoff}, and General Electric\cite{GE}. 


<<gearbox, fig.cap="Mass of three-stage gearboxes versus torque.">>=
#Plot Gearbox data

gearbox <- read.delim("../gearbox/gearbox_data.txt")
colors = brewer.pal(4,"Dark2")

plot(gearbox$Torque.kNm, gearbox$Weight.kg/1000, pch=as.numeric(gearbox$Manufacturer)+21, 
     las=1, col=colors[gearbox$Manufacturer], bty="l", xlim=c(0,6000), ylim=c(0,62),
     xlab="Torque (kNm)", ylab="Mass (t)")
grid()

#Add Legend
legend(3600,45, legend=levels(gearbox$Manufacturer), col=colors,pch=22:25,
     bty="n", ncol=1, cex=0.8, pt.cex=1, x.intersp=0.4)

linear_estimation<-lm(Weight.kg/1000 ~ Torque.kNm, data=gearbox)
abline(linear_estimation, col="gray", lwd=2, lty=2)
# display equation
linear_coefficients <- round(coef(linear_estimation), 3) 
#mtext(bquote(Mass(t) == .(linear_coefficients[2])*Torque (kNm) + .(linear_coefficients[1])), 
 #     adj=1, padj=0)
@
\begin{equation}
\text{Mass(t)} = 0.011 \times T_{in} + 3.7
\label{3G_gearbox}
\end{equation}

\subsection{Structural Components}

\subsubsection{Low Speed Shaft}
Low speed shaft is not a critical component; it connects the main hub to gearbox or generator. Low speed shaft is not required for some drive train options (e.g. integrated bearing type). The mass and the cost of the low speed shaft as a function of the rotor diameter can be expressed as \cite{Fingersh2006}:

\begin{equation}
	\text{Mass (t)} = 1.35 \times {P_{rated}}^{1.44}
\end{equation}

\subsectiion{Main Bearing}

The mass of the main bearing can vary depending on the bearing type. For example, a double-tapered roller bearing for a direct-drive is heavier than a conventional two-point suspension type bearing. To give and idea the mass of a conventional bearing that is connected to a three-stage gearbox can be estimated as \cite{Fingersh2006};

\begin{equation}
	\text{Mass(t)} = 130 \times {P_{rated}}^{1.75}
\end{equation}

\subsection{Hydraulic Systems}

\subsection{Generator}
The generator types covered are induction generator, permanent-magnet generator, synchronous generator and superconducting generator. The cooling method for the generators are also defined (air or water cooled). 
All these data are combined in an open-source design tool. The user can select different PTO systems, and then define the input power and rotational speed The design tool gives the mass and efficiency of the components. Thus, it is very easy for a user to compare different PTO systems and modify the mechanical models based on these estimations. The design tool is built using Matlab GUI. The aim of the study is to publish it as a web application that is open to wind turbine designers. We aim to expand the toolbox for the reliability calculation of the different PTO systems. The design tool will help the designers to compare different PTO systems and select the most suitable option for the specific application.

<<induction_generator,  fig.cap="Mass of the induction generator vs torque.">>=
#Plot High Speed Induction Generator
induction_generator <- read.delim("../generator/induction-generator-data.txt")
colors = brewer.pal(3,"Dark2")
plot(induction_generator$Power.MW, induction_generator$Mass.t, pch=as.numeric(induction_generator$Manufacturer)+21, 
     lwd=1, col=colors[induction_generator$Manufacturer], bty="l", xlim=c(0,8), ylim=c(0,16),las=1,xlab="Power (MW)", ylab="Mass (t)")
grid()
#Add Legend
legend(3.6,8.5, legend=c("ABB", "Siemens (Air cooled)", "Siemens (Water cooled)"), col=colors,pch=22:25, cex=0.8,pt.cex=1,lty=0, bty="n", x.intersp=0.4, ncol=1)

#Air cooled Siemens Machines
subset_data <- subset(induction_generator, Manufacturer=="Siemens-air", c(Power.MW, Mass.t))
# Non-linear modeln(power fit)
fit <- nls(Mass.t ~ a*Power.MW^b,data = subset_data,start = list(a = 3, b = 1))
#Plot power estimation
power_fine <- seq(0, 7.5, length = 101)
lines(power_fine, predict(fit, list(Power.MW= power_fine)), lty=2,lwd=2, col=colors[2])

#coefficients <- round(coef(fit), 2) 
#mtext(paste("Mass(t)=",coefficients[1],"xPower(MW)^",coefficients[2], sep=""), 3,-3.5)

#Water cooled Siemens Machines
subset_data <- subset(induction_generator, Manufacturer=="Siemens-water", c(Power.MW, Mass.t))
# Non-linear modeln(power fit)
fit <- nls(Mass.t ~ a*Power.MW^b,data = subset_data,start = list(a = 3, b = 1))
#Plot power estimation
power_fine <- seq(0, 7.5, length = 101)
lines(power_fine, predict(fit, list(Power.MW= power_fine)), lty=2,lwd=2, col=colors[3])

#coefficients <- round(coef(fit), 2) 
#mtext(paste("Mass(t)=",coefficients[1],"xPower(MW)^",coefficients[2], sep=""), 1,-6.5)
@

<<induction_generator_eeficiency,  fig.cap="Mass of the induction generator vs torque.">>=

#Set colors
colors = brewer.pal(3,"Dark2")

plot(induction_generator$Power.MW, induction_generator$Efficiency.full, 
     pch=as.numeric(induction_generator$Manufacturer)+21, 
     col=colors[induction_generator$Manufacturer], bty="l", xlim=c(0,8), ylim=c(95,98),yaxt="n", las=1,xlab="Power (MW)", ylab="Efficiency (%)")
axis(2, at=c(95,96,97,98),las=1)
grid()

legend(3.5,96.2, legend=c("Siemens (Air cooled)", "Siemens (Water cooled)"), 
       col=colors[2:3], pch=23:25,cex=0.8,pt.cex=1,lty=0, x.intersp=0.4, ncol=1, bty="n")

#Siemens Machines
subset_data <- subset(induction_generator, Manufacturer!="ABB", c(Power.MW, Mass.t))
# Non-linear modeln(power fit)
fit <- nls(Efficiency.full ~ a*Power.MW^b,data = induction_generator, 
         start=list(a = 95, b = 0.01))
#Plot power estimation
power_fine <- seq(0, 7.5, length = 101)
lines(power_fine, predict(fit, list(Power.MW= power_fine)), lty=2,lwd=2, col="darkgray")

#coefficients <- round(coef(fit), 2) 
#mtext(paste("Efficiency (%)=",coefficients[1],"xPower(MW)^",coefficients[2], sep=""), 3,-3.5)
@

\begin{equation}
  \text{Mass}_{air}(t) = 3.91 \times {P_{rated}}^{0.69}
\end{equation}

\begin{equation}
  \text{Mass}_{water}(t) = 3.22 \times {P_{rated}}^{0.68}
\end{equation}

\begin{equation}
\text{Efficiency (\%)} = 95.64 \times {P_{rated}}^{0.01}
\end{equation}



<<plot1gpm, fig.cap="Mass of the medium speed permanent magnet generator vs torque.">>=
g1pm_generator <- read.delim("../generator/1GPM-generator-data.txt")
#Set colors
colors = brewer.pal(3,"Dark2")
plot(g1pm_generator$Torque.kNm, g1pm_generator$Mass.t,pch=21, cex=1.5, 
     col=colors[1], bty="l", las=1,
     xlab="Torque (kNm)", ylab="Mass (t)")
#grid()
linear_estimation<-lm(Mass.t ~ Torque.kNm, data=g1pm_generator)
abline(linear_estimation, col="gray", lwd=2, lty=2)
# display equation
linear_coefficients <- round(coef(linear_estimation), 3) 
mtext(bquote(Mass(t) == .(linear_coefficients[2])*Torque (kNm) + .(round(linear_coefficients[1],1))), adj=1, padj=3, cex=0.8)
@


\subsection{Direct Drive Synchronous Generator}

\begin{equation}
  \text{Mass(t)} = 0.035 \times {T_{rated}} + 8.9
\end{equation}

\subsection{Permanent Magnet Generator}

\subsubsection{Direct Drive}

\begin{equation}
  \text{Mass(t)} = 0.028 \times {T_{rated}} + 2.8
\end{equation}


\subsubsection{Medium Speed}

\begin{equation}
  \text{Mass(t)} = 0.03 \times {T_{rated}} + 1.5
\end{equation}

As shonw in \autoref{fig:plot1gpm}

The proceedings for IE 07 will contain all the accepted
papers following the peer review process. Authors are
asked to prepare and submit the {\bf PDF} electronic versions
of their full papers according to the instructions below.

\section{Manuscript preparation}
Full papers must be typed in English. The title of the
paper is typed in CAPITAL LETTERS (boldface 18pt)
and centred on the page. The author's name is typed in
capital and lower case bold letters and centred on the
page. Directly under the author's name in capital and
lower case letters and also centred is the author's
affiliation, address, plus e-mail address and fax number of
(at least) the corresponding author. Manuscripts must be
typed single spaced using 10 point characters. Only
Times, Times Roman, Times New Roman and Symbol
fonts are accepted. The text should be typed on an A4
paper (21 cm x 29.7 cm). The paper should have margins
of 2.4 cm from top and bottom and 2 cm from left and
right. Paragraphs are separated by 6 points and with no
indentation. The text of the full papers is written in two
columns and justified. Each column has a width of 8.3 cm
and the columns are separated by a margin of 0.4 cm. The
maximum length of the full paper is 8 pages, of the short
and the demo paper 4 pages. Do not number the pages.
The final format in which the papers will appear on the
CD ROM will be a PDF file. Authors are requested to send
a PDF file of their final paper to be included directly
in the CD ROM.

\subsection{Figures and tables}
Figures and tables should be centred in the column,
numbered consecutively throughout the text, and each
should have a caption underneath it (see for example
Table~\ref{tab1}). Care should be taken that the lettering
is not too small. All figures and tables should be included
in the electronic versions of the full paper.


\begin{table}[htb!]
\begin{center}

\begin{tabular}{|l|l|}
\hline
{\em n} & {\em n!} \\
\hline
1 & 1  \\
2 & 2  \\
3  & 6\\
\hline
\end{tabular}
\end{center}
\caption{\label{tab1}This is an example of a table caption.}
\end{table}

\subsubsection{Equations}
Equations should be typed within the text, centred, and
should be numbered consecutively throughout the text.
They should be referred to in the text as Equation (n).
Their numbers should be typed in parentheses, flush right,
as in the following example.
\begin{equation}
	    PA + A'P - PBR^{-1}B'P + Q  =  0 \enspace.
\end{equation}

\subsubsection{References}
The list of references should be ordered alphabetically
according to the first author surname. All references
should be cited in the text, and using square brackets such
as \cite{ref01} and \cite{ref02}.

\section{Generating a {PDF} file}
The PDF format will be the final format under which the
papers will appear in the {CD ROM}. You {\bf SHOULD}
submit your paper as {PDF} document.

\section{Electronic submission of the full paper}
You should submit your {PDF} file which should adhere to
the above format via the conference paper submission
system.

\section*{Acknowledgements}
The acknowledgement for funding organisations etc.
should be placed in a separate section at the end of the
text. Thank you for your cooperation in complying with
these instructions.

\bibliography{ie07}
\noindent
\bibliographystyle{plain}

\end{document}