function varargout = MARINA_GUI_WP7_2(varargin)
% MARINA_GUI_WP7_2 MATLAB code for MARINA_GUI_WP7_2.fig
%      MARINA_GUI_WP7_2, by itself, creates a new MARINA_GUI_WP7_2 or raises the existing
%      singleton*.
%
%      H = MARINA_GUI_WP7_2 returns the handle to a new MARINA_GUI_WP7_2 or the handle to
%      the existing singleton*.
%
%      MARINA_GUI_WP7_2('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in MARINA_GUI_WP7_2.M with the given input arguments.
%
%      MARINA_GUI_WP7_2('Property','Value',...) creates a new MARINA_GUI_WP7_2 or raises
%      the existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before MARINA_GUI_WP7_2_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to MARINA_GUI_WP7_2_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help MARINA_GUI_WP7_2

% Last Modified by GUIDE v2.5 08-Oct-2012 16:09:46

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @MARINA_GUI_WP7_2_OpeningFcn, ...
                   'gui_OutputFcn',  @MARINA_GUI_WP7_2_OutputFcn, ...
                   'gui_LayoutFcn',  @MARINA_GUI_WP7_2_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT

% --- Executes just before MARINA_GUI_WP7_2 is made visible.
function MARINA_GUI_WP7_2_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to MARINA_GUI_WP7_2 (see VARARGIN)

% Choose default command line output for MARINA_GUI_WP7_2
handles.output = hObject;

%DEFAULT VARIABLES
%handles.generator='PMG';        %Induction Generator

%Write initial values
set(handles.power,'string',num2str(3.0));
set(handles.speed,'string',num2str(14));


%generator type
handles.val.generator='IG';  %default generator type induction generator

%Modify Gearbox Options
set(handles.DD, 'Enable', 'off');
set(handles.hydraulic_gear, 'Enable', 'off');       

%cooling
handles.val.cooling='air';

%gearbox
handles.val.gearbox='multi_stage';

%Get initial values to val argument
handles.val.power=str2double(get(handles.power, 'String'));
handles.val.speed=str2double(get(handles.speed, 'String'));
% 
% handles.pair_type = get(hObject,'tag');
% guidata(hObject, handles);


% Update handles structure
guidata(hObject, handles);

initialize_gui(hObject, handles, false);

% UIWAIT makes MARINA_GUI_WP7_2 wait for user response (see UIRESUME)
% uiwait(handles.figure1);

%ARKA PLAN RESMI EKLEMECE
% create an axes that spans the whole gui
%ah = axes('unit', 'normalized', 'position', [0.6 0.5 0.35 0.4]); 
% import the background image and show it on the axes
%bg = imread('./images/DFIG_3G.png'); imagesc(bg);
% prevent plotting over the background and turn the axis off
%set(ah,'handlevisibility','off','visible','off')
% making sure the background is behind all the other uicontrols
%uistack(ah, 'bottom');

axes(handles.ViewBox1);
image1=imread('./images/DFIG_3G.png');
image(image1);
axis off;
axis image;
%imshow(image1);
 

% --- Outputs from this function are returned to the command line.
function varargout = MARINA_GUI_WP7_2_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;


% --- Executes during object creation, after setting all properties.
function power_CreateFcn(hObject, eventdata, handles)
% hObject    handle to power (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function power_Callback(hObject, eventdata, handles)
% hObject    handle to power (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of power as text
%        str2double(get(hObject,'String')) returns contents of power as a double
handles.val.power = str2double(get(hObject, 'String'));
if isnan(handles.val.power)
    set(hObject, 'String', 0);
    errordlg('Input must be a number','Error');
end

guidata(hObject,handles)

% --- Executes during object creation, after setting all properties.
function speed_CreateFcn(hObject, eventdata, handles)
% hObject    handle to speed (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function speed_Callback(hObject, eventdata, handles)
% hObject    handle to speed (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of speed as text
%        str2double(get(hObject,'String')) returns contents of speed as a double
handles.val.speed = str2double(get(hObject, 'String'));
if isnan(handles.val.speed)
    set(hObject, 'String', 0);
    errordlg('Input must be a number','Error');
end

% Save the new speed value
guidata(hObject,handles)

% --- Executes on button press in calculate.
function calculate_Callback(hObject, eventdata, handles)
% hObject    handle to calculate (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

%GEARBOX
%gearbox(gear_ratio,torque,speed)
%input torque
torque=handles.val.power*30/(pi*handles.val.speed)*1e6;  %Torque(Nm)= Power/w

switch handles.val.gearbox % Generator Type
    case 'DD'
        handles.val.gearbox_mass=0;
        handles.val.gearbox_efficiency=1;
        handles.val.generator_speed=handles.val.speed; %Generator speed same with turbine speed
        
    case 'single_stage'  %UPDATE
        handles.val.gear_ratio=4.84*handles.val.power^0.26; %function of gear ratio as a function of power from Upwind Report
        handles.val.generator_speed=handles.val.gear_ratio*handles.val.speed;

        [handles.val.gearbox_efficiency,handles.val.gearbox_mass,handles.val.gearbox_cost]=gearbox(handles.val.gear_ratio,torque,handles.val.speed);
        
    case 'multi_stage'
        handles.val.generator_speed=1500; %assume a 1500 rpm machine
        handles.val.gear_ratio=handles.val.generator_speed/handles.val.speed; 
        
        [handles.val.gearbox_efficiency,handles.val.gearbox_mass,handles.val.gearbox_cost]=gearbox(handles.val.gear_ratio,torque,handles.val.speed);
    
    case 'hydraulic_gear'   
        handles.val.generator_speed=1500; %assume a 1500 rpm synchronous machine
        handles.val.gearbox_mass=10;
        [handles.val.gearbox_efficiency,handles.val.gearbox_mass]=hydraulic(handles.val.power,handles.val.speed);
end

set(handles.gearbox_mass, 'string', num2str(handles.val.gearbox_mass));  


%GENERATOR
switch handles.val.generator % Generator Type
    case 'IG'
        [handles.val.generator_mass,handles.val.generator_efficiency]=induction_generator(handles.val.power,handles.val.generator_speed,handles.val.cooling);
        % Code for when radiobutton1 is selected.
    case 'PMG'
        [handles.val.generator_mass,handles.val.generator_efficiency]=pm_generator(handles.val.power,handles.val.generator_speed,handles.val.cooling);
        
        % Code for when radiobutton2 is selected.
    case 'SG'
        [handles.val.generator_mass,handles.val.generator_efficiency]=eesg_generator(handles.val.power,handles.val.generator_speed,handles.val.cooling);
        % Code for when togglebutton1 is selected.
    case 'hts'
        % Code for when togglebutton2 is selected.
        [handles.val.generator_mass,handles.val.generator_efficiency]=superconducting_generator(handles.val.power,handles.val.speed);
    % Continue with more cases as necessary.
    otherwise
        % Code for when there is no match.
end

set(handles.generator_mass, 'string', num2str(handles.val.generator_mass));


%BEARING
handles.val.bearing_mass=main_bearing(handles.val.power);
set(handles.bearing_mass, 'string', num2str(handles.val.bearing_mass));

%LOW SPEED SHAFT
%cost may be added
if strcmp(handles.val.gearbox,'DD')
    handles.val.shaft_mass=0;
else
    handles.val.shaft_mass=low_speed_shaft(handles.val.power);
end
set(handles.shaft_mass, 'string', num2str(handles.val.shaft_mass));


%Calculate total mass
handles.val.total_mass=round(10*(handles.val.gearbox_mass+handles.val.generator_mass+handles.val.bearing_mass+handles.val.shaft_mass)/1000)/10;
set(handles.total_mass, 'string', num2str(handles.val.total_mass));

%Write Efficiency Values
set(handles.gearbox_eff, 'string', num2str(100*handles.val.gearbox_efficiency));
set(handles.generator_eff, 'string', num2str(100*handles.val.generator_efficiency));
%Overall efficiency
set(handles.total_eff, 'string', num2str(round(100*100*handles.val.generator_efficiency*handles.val.gearbox_efficiency)/100));

% --- Executes on button press in reset.
function reset_Callback(hObject, eventdata, handles)
% hObject    handle to reset (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

%Reset default values
%DEFAULT VARIABLES
%handles.generator='PMG';        %Induction Generator

%Write initial values
set(handles.power,'string',num2str(3.0));
set(handles.speed,'string',num2str(14));


%generator type
handles.val.generator='IG';  %default generator type induction generator
set(handles.IG, 'Value', 1);

%Modify Gearbox Options
set(handles.DD, 'Enable', 'off');
set(handles.hydraulic_gear, 'Enable', 'off');       

%cooling
handles.val.cooling='air';
set(handles.air, 'Value', 1);
%gearbox
handles.val.gearbox='multi_stage';
set(handles.multi_stage, 'Value', 1);

%Get initial values to val argument
handles.val.power=str2double(get(handles.power, 'String'));
handles.val.speed=str2double(get(handles.speed, 'String'));


%update image
axes(handles.ViewBox1);
image1=imread('./images/DFIG_3G.png');
image(image1);
axis off;
axis image;

calculate_Callback(hObject, eventdata, handles)


% --------------------------------------------------------------------
function initialize_gui(fig_handle, handles, isreset)
% If the metricdata field is present and the reset flag is false, it means
% we are we are just re-initializing a GUI by calling it from the cmd line
% while it is up. So, bail out as we dont want to reset the data.
if isfield(handles, 'metricdata') && ~isreset
    return;
end


% --- Executes during object creation, after setting all properties.
function edit6_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit6 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes during object creation, after setting all properties.
function edit7_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit7 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



% --- Executes during object creation, after setting all properties.
function gearbox_eff_CreateFcn(hObject, eventdata, handles)
% hObject    handle to gearbox_eff (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes during object creation, after setting all properties.
function generator_eff_CreateFcn(hObject, eventdata, handles)
% hObject    handle to generator_eff (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes during object creation, after setting all properties.
function total_eff_CreateFcn(hObject, eventdata, handles)
% hObject    handle to total_eff (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes during object creation, after setting all properties.
function gearbox_mass_CreateFcn(hObject, eventdata, handles)
% hObject    handle to gearbox_mass (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes during object creation, after setting all properties.
function generator_mass_CreateFcn(hObject, eventdata, handles)
% hObject    handle to generator_mass (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes during object creation, after setting all properties.
function bearing_mass_CreateFcn(hObject, eventdata, handles)
% hObject    handle to bearing_mass (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

% --- Executes during object creation, after setting all properties.
function total_mass_CreateFcn(hObject, eventdata, handles)
% hObject    handle to total_mass (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes when selected object is changed in generator.
function generator_SelectionChangeFcn(hObject, eventdata, handles)
% hObject    handle to the selected object in generator 
% eventdata  structure with the following fields (see UIBUTTONGROUP)
%	EventName: string 'SelectionChanged' (read only)
%	OldValue: handle of the previously selected object or empty if none was selected
%	NewValue: handle of the currently selected object
% handles    structure with handles and user data (see GUIDATA)

switch get(eventdata.NewValue,'Tag') % Get Tag of selected object.
    case 'IG'
        handles.val.generator='IG';
        %Modify Gearbox Options
        set(handles.DD, 'Enable', 'off');
        set(handles.single_stage, 'Enable', 'on');
        set(handles.multi_stage, 'Enable', 'on');
        set(handles.hydraulic_gear, 'Enable', 'off');
        
        %enable cooling
        set(handles.air, 'Enable', 'on');
        set(handles.water, 'Enable', 'on');
                
        set(handles.multi_stage, 'Value', 1);
        handles.val.gearbox='multi_stage';
        
        %update image
        image1=imread('./images/DFIG_3G.png');
 
    case 'PMG'
        handles.val.generator='PMG';
        %Modify Gearbox Options
        set(handles.DD, 'Enable', 'on');
        set(handles.single_stage, 'Enable', 'on');
        set(handles.multi_stage, 'Enable', 'on');
        set(handles.hydraulic_gear, 'Enable', 'off');
        
        %disable cooling
        set(handles.air, 'Enable', 'off');
        set(handles.water, 'Enable', 'off');
        
        set(handles.DD, 'Value', 1);            
        handles.val.gearbox='DD';
        %update image
        image1=imread('./images/DDPMG.png');
      
    case 'SG'
        handles.val.generator='SG';
        %Modify Gearbox Options
        set(handles.DD, 'Enable', 'on');
        set(handles.single_stage, 'Enable', 'off');
        set(handles.multi_stage, 'Enable', 'on');
        set(handles.hydraulic_gear, 'Enable', 'on');    
        
        %enable cooling
        set(handles.air, 'Enable', 'on');
        set(handles.water, 'Enable', 'on');
                
        set(handles.multi_stage, 'Value', 1);
        handles.val.gearbox='multi_stage';

        %update image                
        image1=imread('./images/EESG_3G.png');

    case 'hts'
        handles.val.generator='hts';       
        %Modify Gearbox Options
        set(handles.DD, 'Enable', 'on');
        set(handles.single_stage, 'Enable', 'off');
        set(handles.multi_stage, 'Enable', 'off');
        set(handles.hydraulic_gear, 'Enable', 'off');
        
        %disable cooling
        set(handles.air, 'Enable', 'off');
        set(handles.water, 'Enable', 'off');
        
        %default selection
        set(handles.DD, 'Value', 1);
        handles.val.gearbox='DD';
        %update image
        image1=imread('./images/HTSG.png');
end

        %plot image
        axes(handles.ViewBox1);
        image(image1);
        axis off;
        axis image;
        
guidata(hObject,handles)


% --- Executes when selected object is changed in cooling.
function cooling_SelectionChangeFcn(hObject, eventdata, handles)
% hObject    handle to the selected object in cooling 
% eventdata  structure with the following fields (see UIBUTTONGROUP)
%	EventName: string 'SelectionChanged' (read only)
%	OldValue: handle of the previously selected object or empty if none was selected
%	NewValue: handle of the currently selected object
% handles    structure with handles and user data (see GUIDATA)
switch get(eventdata.NewValue,'Tag') % Get Tag of selected object.
    case 'air'
        handles.val.cooling='air';
       % Code for when radiobutton1 is selected.
    case 'water'
        handles.val.cooling='water';
        % Code for when radiobutton2 is selected.
    otherwise
        % Code for when there is no match.
end
guidata(hObject,handles)


% --- Executes when selected object is changed in gearbox.
function gearbox_SelectionChangeFcn(hObject, eventdata, handles)
% hObject    handle to the selected object in gearbox 
% eventdata  structure with the following fields (see UIBUTTONGROUP)
%	EventName: string 'SelectionChanged' (read only)
%	OldValue: handle of the previously selected object or empty if none was selected
%	NewValue: handle of the currently selected object
% handles    structure with handles and user data (see GUIDATA)
switch get(eventdata.NewValue,'Tag') % Get Tag of selected object.
    
    case 'DD'
        handles.val.gearbox='DD';
        %Generator type
        %update image
        switch handles.val.generator
            case 'SG'
                 image1=imread('./images/EESG.png');      
            case 'PMG'
                  image1=imread('./images/DDPMG.png');
            case 'hts'
                  image1=imread('./images/HTSG.png');
        end                
        
    case 'single_stage'
        handles.val.gearbox='single_stage';
        
        %update image
        switch handles.val.generator
            case 'IG'
                 image1=imread('./images/DFIG_1G.png');      
            case 'PMG'
                  image1=imread('./images/PMG_1G.png');
        end

                    

    case 'multi_stage'
        handles.val.gearbox='multi_stage';
        
        %update image
        switch handles.val.generator
            case 'SG'
                 image1=imread('./images/EESG_3G.png');      
            case 'PMG'
                  image1=imread('./images/PMG_3G.png');
            case 'IG'
                  image1=imread('./images/DFIG_3G.png');
        end
        % Code for when togglebutton1 is selected.
    case 'hydraulic_gear'
        handles.val.gearbox='hydraulic_gear';
        %update image
        image1=imread('./images/EESG_hydraulics.png');
        % Code for when togglebutton2 is selected.
    % Continue with more cases as necessary.
    otherwise
        % Code for when there is no match.
end
           %Write image     
           axes(handles.ViewBox1);
           image(image1);
           axis off;
           axis image;
guidata(hObject,handles)


% --- Creates and returns a handle to the GUI figure. 
function h1 = MARINA_GUI_WP7_2_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end
load MARINA_GUI_WP7_2.mat


appdata = [];
appdata.GUIDEOptions = mat{1};
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Color',[1 1 1],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'DockControls','off',...
'IntegerHandle','off',...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'MenuBar','none',...
'Name','marina_gui',...
'NumberTitle','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',[20.98404194812 29.67743169791],...
'PaperType',get(0,'defaultfigurePaperType'),...
'Position',[0 -9 666 469],...
'Resize','off',...
'HandleVisibility','callback',...
'Tag','figure1',...
'UserData',[],...
'Visible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_1';

h2 = uimenu(...
'Parent',h1,...
'Callback',mat{2},...
'Label','Untitled 1',...
'Tag','Untitled_1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'drive_train';

h3 = uibuttongroup(...
'Parent',h1,...
'Units','pixels',...
'FontUnits','pixels',...
'FontSize',14,...
'FontWeight','bold',...
'Title','Type of Drive Train',...
'Tag','drive_train',...
'Clipping','on',...
'BackgroundColor',[1 1 1],...
'Position',[7 7 453 430],...
'SelectedObject',[],...
'SelectionChangeFcn',[],...
'OldSelectedObject',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'generator';

h4 = uibuttongroup(...
'Parent',h3,...
'Units','pixels',...
'FontUnits','pixels',...
'FontSize',13,...
'FontWeight','bold',...
'Title','Generator',...
'Tag','generator',...
'Clipping','on',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'Position',[9 11 220 193],...
'SelectedObject',[],...
'SelectionChangeFcn',mat{3},...
'OldSelectedObject',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'IG';

h5 = uicontrol(...
'Parent',h4,...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',13,...
'Position',[4 139 160 29],...
'String','Induction Generator',...
'Style','radiobutton',...
'Value',1,...
'Tag','IG',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'PMG';

h6 = uicontrol(...
'Parent',h4,...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',13,...
'Position',[4 109 206 29],...
'String','Permanent-Magnet Generator',...
'Style','radiobutton',...
'Tag','PMG',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SG';

h7 = uicontrol(...
'Parent',h4,...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',13,...
'Position',[4 79 160 29],...
'String','Synchronous Generator',...
'Style','radiobutton',...
'Tag','SG',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'hts';

h8 = uicontrol(...
'Parent',h4,...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',13,...
'Position',[4 49 194 29],...
'String','Superconducting Generator',...
'Style','radiobutton',...
'Tag','hts',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'cooling';

h9 = uibuttongroup(...
'Parent',h4,...
'Units','pixels',...
'FontUnits','pixels',...
'FontSize',11.8055555555556,...
'Title','Cooling',...
'Tag','cooling',...
'Clipping','on',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'Position',[4 8 211 42],...
'SelectedObject',[],...
'SelectionChangeFcn',mat{8},...
'OldSelectedObject',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'air';

h10 = uicontrol(...
'Parent',h9,...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',12,...
'Position',[7 5 108 20],...
'String','Air Cooled',...
'Style','radiobutton',...
'Value',1,...
'Tag','air',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'water';

h11 = uicontrol(...
'Parent',h9,...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',12,...
'Position',[96 5 106 20],...
'String','Water Cooled',...
'Style','radiobutton',...
'Tag','water',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'gearbox';

h12 = uibuttongroup(...
'Parent',h3,...
'Units','pixels',...
'FontUnits','pixels',...
'FontSize',13,...
'FontWeight','bold',...
'Title','Gearbox',...
'Tag','gearbox',...
'UserData',[],...
'Clipping','on',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'Position',[238 61 206 142],...
'SelectedObject',[],...
'SelectionChangeFcn',mat{11},...
'OldSelectedObject',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'hydraulic_gear';

h13 = uicontrol(...
'Parent',h12,...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',13,...
'Position',[9 4 138 29],...
'String','Hydraulic Gearbox',...
'Style','radiobutton',...
'Tag','hydraulic_gear',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'multi_stage';

h14 = uicontrol(...
'Parent',h12,...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',13,...
'Position',[9 65 138 29],...
'String','Multi-Stage Gearbox',...
'Style','radiobutton',...
'Value',1,...
'Tag','multi_stage',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'single_stage';

h15 = uicontrol(...
'Parent',h12,...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',13,...
'Position',[9 34 164 29],...
'String','Single-Stage Gearbox',...
'Style','radiobutton',...
'Tag','single_stage',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'DD';

h16 = uicontrol(...
'Parent',h12,...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',13,...
'Position',[9 96 187 27],...
'String','No Gearbox (Direct-Drive)',...
'Style','radiobutton',...
'Tag','DD',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'ViewBox1';

h17 = axes(...
'Parent',h3,...
'Units','pixels',...
'FontUnits','pixels',...
'Position',[22 205.5 396 198],...
'ALim',get(0,'defaultaxesALim'),...
'ALimMode','manual',...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color',get(0,'defaultaxesColor'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'FontSize',11.8055555555556,...
'LooseInset',[104 52.8 76 36],...
'XColor',get(0,'defaultaxesXColor'),...
'YColor',get(0,'defaultaxesYColor'),...
'ZColor',get(0,'defaultaxesZColor'),...
'Tag','ViewBox1',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h18 = get(h17,'title');

set(h18,...
'Parent',h17,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.498737373737374 1.02777777777778 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h19 = get(h17,'xlabel');

set(h19,...
'Parent',h17,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.498737373737374 -0.113636363636364 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h20 = get(h17,'ylabel');

set(h20,...
'Parent',h17,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.0694444444444444 0.492424242424242 1.00005459937205],...
'Rotation',90,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h21 = get(h17,'zlabel');

set(h21,...
'Parent',h17,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.0744949494949495 1.29040404040404 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','middle',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','off',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.lastValidTag = 'reset';

h22 = uicontrol(...
'Parent',h3,...
'FontUnits','pixels',...
'BackgroundColor',[0.96078431372549 0.976470588235294 0.992156862745098],...
'Callback',mat{16},...
'CData',[],...
'FontSize',14,...
'FontWeight','bold',...
'ListboxTop',0,...
'Position',[246 13.5 85 40],...
'String','Reset',...
'Tag','reset',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'calculate';

h23 = uicontrol(...
'Parent',h3,...
'FontUnits','pixels',...
'BackgroundColor',[0.83921568627451 0.909803921568627 0.850980392156863],...
'Callback',mat{17},...
'CData',[],...
'FontSize',14,...
'FontWeight','bold',...
'ListboxTop',0,...
'Position',[345 13.5 85 40],...
'String','Calculate',...
'Tag','calculate',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'mass_output';

h24 = uibuttongroup(...
'Parent',h1,...
'Units','pixels',...
'FontUnits','pixels',...
'FontSize',14,...
'FontWeight','bold',...
'Title','Drive Train Mass',...
'Tag','mass_output',...
'Clipping','on',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'Position',[473 10.3333333333333 192 181],...
'SelectedObject',[],...
'SelectionChangeFcn',[],...
'OldSelectedObject',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text23';

h25 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',11.8055555555556,...
'HorizontalAlignment','left',...
'Position',[2.8 10.0769230769231 10.4 1.23076923076923],...
'String','Gearbox',...
'Style','text',...
'Tag','text23',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text24';

h26 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',11.8055555555556,...
'HorizontalAlignment','left',...
'Position',[2.8 7.53846153846154 13.4 1.23076923076923],...
'String','Generator',...
'Style','text',...
'Tag','text24',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text25';

h27 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',11.8055555555556,...
'HorizontalAlignment','left',...
'Position',[2.8 5.23076923076923 10 1.07692307692308],...
'String','Bearing',...
'Style','text',...
'Tag','text25',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'gearbox_mass';

h28 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[1 1 1],...
'Callback',mat{18},...
'FontSize',11.8055555555556,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[17.4333333333333 9.9423076923077 9 2],...
'String','0',...
'Style','text',...
'CreateFcn',mat{19},...
'Tag','gearbox_mass');

local_CreateFcn(h28, [], '', appdata);

appdata = [];
appdata.lastValidTag = 'generator_mass';

h29 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[1 1 1],...
'Callback',mat{20},...
'FontSize',11.8055555555556,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[17.4333333333333 7.4423076923077 9 2],...
'String','0',...
'Style','text',...
'CreateFcn',mat{21},...
'Tag','generator_mass');

local_CreateFcn(h29, [], '', appdata);

appdata = [];
appdata.lastValidTag = 'bearing_mass';

h30 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[1 1 1],...
'Callback',mat{22},...
'FontSize',11.8055555555556,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[17.4333333333333 4.94230769230769 9 2],...
'String','0',...
'Style','text',...
'CreateFcn',mat{23},...
'Tag','bearing_mass');

local_CreateFcn(h30, [], '', appdata);

appdata = [];
appdata.lastValidTag = 'text27';

h31 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',11.8055555555556,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[28.8 9.53846153846154 4 2.07692307692308],...
'String','kg',...
'Style','text',...
'Tag','text27',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text28';

h32 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',11.8055555555556,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[28.8 7 4 2.07692307692308],...
'String','kg',...
'Style','text',...
'Tag','text28',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text29';

h33 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',11.8055555555556,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[28.8333333333333 4.52564102564102 4 2.08333333333333],...
'String','kg',...
'Style','text',...
'Tag','text29',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text39';

h34 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',14,...
'FontWeight','bold',...
'Position',[1.8 0.461538461538462 15.6 1.46153846153846],...
'String','Total Mass',...
'Style','text',...
'Tag','text39',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'total_mass';

h35 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[1 1 1],...
'Callback',mat{24},...
'FontSize',16,...
'FontWeight','bold',...
'ListboxTop',0,...
'Position',[19.4 0.230769230769231 10 2],...
'String','0',...
'Style','text',...
'Value',1,...
'CreateFcn',mat{25},...
'Tag','total_mass');

local_CreateFcn(h35, [], '', appdata);

appdata = [];
appdata.lastValidTag = 'text43';

h36 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',11.8055555555556,...
'HorizontalAlignment','left',...
'Position',[2.8 2.69230769230769 10 1.07692307692308],...
'String','Shaft',...
'Style','text',...
'Tag','text43',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'shaft_mass';

h37 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[1 1 1],...
'Callback',mat{26},...
'FontSize',11.8055555555556,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[17.4333333333333 2.44230769230771 9 2],...
'String','0',...
'Style','text',...
'Tag','shaft_mass',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text45';

h38 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',11.8055555555556,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[28.8333333333333 2.02564102564104 4 2.08333333333333],...
'String','kg',...
'Style','text',...
'Tag','text45',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text40';

h39 = uicontrol(...
'Parent',h24,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',14,...
'FontWeight','bold',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[28.8 0.461538461538462 3.4 1.53846153846154],...
'String','t',...
'Style','text',...
'Tag','text40',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel18';

h40 = uibuttongroup(...
'Parent',h1,...
'Units','pixels',...
'FontUnits','pixels',...
'FontSize',14,...
'FontWeight','bold',...
'Title','Drive Train Efficiency',...
'Tag','uipanel18',...
'UserData',[],...
'Clipping','on',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'Position',[475 195 192 122],...
'SelectedObject',[],...
'SelectionChangeFcn',[],...
'OldSelectedObject',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text31';

h41 = uicontrol(...
'Parent',h40,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',13,...
'HorizontalAlignment','left',...
'Position',[2 6.46153846153847 13.4 1.38461538461538],...
'String','Gearbox',...
'Style','text',...
'Tag','text31',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text32';

h42 = uicontrol(...
'Parent',h40,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',13,...
'HorizontalAlignment','left',...
'Position',[2 4.23076923076923 14.4 1.38461538461538],...
'String','Generator',...
'Style','text',...
'Tag','text32',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'generator_eff';

h43 = uicontrol(...
'Parent',h40,...
'FontUnits','pixels',...
'BackgroundColor',[1 1 1],...
'Callback',mat{27},...
'FontSize',11.8055555555556,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[91 47 45 27],...
'String','0',...
'Style','text',...
'CreateFcn',mat{28},...
'Tag','generator_eff');

local_CreateFcn(h43, [], '', appdata);

appdata = [];
appdata.lastValidTag = 'text41';

h44 = uicontrol(...
'Parent',h40,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',14,...
'FontWeight','bold',...
'Position',[2 1.30769230769231 16.4 1.46153846153846],...
'String','Efficiency',...
'Style','text',...
'Tag','text41',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'total_eff';

h45 = uicontrol(...
'Parent',h40,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[1 1 1],...
'Callback',mat{29},...
'FontSize',16,...
'FontWeight','bold',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[18 0.769230769230769 9.4 2.23076923076923],...
'String','0',...
'Style','text',...
'CreateFcn',mat{30},...
'Tag','total_eff');

local_CreateFcn(h45, [], '', appdata);

appdata = [];
appdata.lastValidTag = 'gearbox_eff';

h46 = uicontrol(...
'Parent',h40,...
'FontUnits','pixels',...
'BackgroundColor',[1 1 1],...
'Callback',mat{31},...
'FontSize',11.8055555555556,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[91 76.0000000000001 45 27],...
'String','0',...
'Style','text',...
'CreateFcn',mat{32},...
'Tag','gearbox_eff');

local_CreateFcn(h46, [], '', appdata);

appdata = [];
appdata.lastValidTag = 'text46';

h47 = uicontrol(...
'Parent',h40,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',12,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[29.4666666666667 5.92307692307692 4 2.08333333333333],...
'String','%',...
'Style','text',...
'Tag','text46',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text47';

h48 = uicontrol(...
'Parent',h40,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',12,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[29.4666666666667 3.42307692307692 4 2.08333333333333],...
'String','%',...
'Style','text',...
'Tag','text47',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text48';

h49 = uicontrol(...
'Parent',h40,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',12,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[29.4666666666667 0.673076923076923 4 2.08333333333333],...
'String','%',...
'Style','text',...
'Tag','text48',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'rating';

h50 = uipanel(...
'Parent',h1,...
'Units','pixels',...
'FontUnits','pixels',...
'FontSize',14,...
'FontWeight','bold',...
'Title','Power Rating',...
'Tag','rating',...
'UserData',[],...
'Clipping','on',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'Position',[475 328 192 100],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text1';

h51 = uicontrol(...
'Parent',h50,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',14,...
'FontWeight','bold',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[1.8 3.38461538461539 10.6 2.07692307692308],...
'String','Power',...
'Style','text',...
'Tag','text1',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text2';

h52 = uicontrol(...
'Parent',h50,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'CData',[],...
'FontSize',14,...
'FontWeight','bold',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[1.8 0.384615384615385 10.8 1.92307692307692],...
'String','Speed',...
'Style','text',...
'Tag','text2',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'speed';

h53 = uicontrol(...
'Parent',h50,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[1 1 1],...
'Callback',mat{33},...
'FontSize',14,...
'FontWeight','bold',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[14 0.538461538461539 6 2.23076923076923],...
'String','0',...
'Style','edit',...
'CreateFcn',mat{34},...
'Tag','speed');

local_CreateFcn(h53, [], '', appdata);

appdata = [];
appdata.lastValidTag = 'text4';

h54 = uicontrol(...
'Parent',h50,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',14,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[21 3.53846153846154 6 2.07692307692308],...
'String','MW',...
'Style','text',...
'Tag','text4',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text5';

h55 = uicontrol(...
'Parent',h50,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[0.972549019607843 0.972549019607843 0.972549019607843],...
'FontSize',14,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[21 0.230769230769231 7 2.07692307692308],...
'String','RPM',...
'Style','text',...
'Tag','text5',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'power';

h56 = uicontrol(...
'Parent',h50,...
'Units','characters',...
'FontUnits','pixels',...
'BackgroundColor',[1 1 1],...
'Callback',mat{35},...
'FontSize',14,...
'FontWeight','bold',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[14 3.76923076923077 6 2.23076923076923],...
'String','5',...
'Style','edit',...
'CreateFcn',mat{36},...
'Tag','power');

local_CreateFcn(h56, [], '', appdata);

appdata = [];
appdata.lastValidTag = 'text15';

h57 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'BackgroundColor',[1 1 1],...
'FontSize',18,...
'FontWeight','bold',...
'Position',[17 437 640 30],...
'String','MARINA PLATFORM - WP 7.2 - Wind Energy System Components',...
'Style','text',...
'Tag','text15',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   eval(createfcn);
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error('MATLAB:gui_mainfcn:FieldNotFound', 'Could not find field %s in the gui_State struct in GUI M-file %s', gui_StateFields{i}, gui_Mfile);
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % MARINA_GUI_WP7_2
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % MARINA_GUI_WP7_2(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallbak(gui_State, varargin{:})
    % MARINA_GUI_WP7_2('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % MARINA_GUI_WP7_2(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~isa(handle(fig),'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || isprop(fig,'__GUIDEFigure');
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI M-file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = openfig(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    gui_hFigure = openfig(name, singleton, visible);
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallbak(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


